"use client";

import Link from "next/link";
import {
  Shield,
  FileSearch,
  BarChart3,
  ArrowRight,
  Database,
  Brain,
  CheckCircle2,
  Lock,
} from "lucide-react";

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-slate-50 flex flex-col font-sans text-slate-900">
      {/* Enterprise Header */}
      <header className="bg-slate-900 text-white border-b border-slate-800 shrink-0">
        <div className="max-w-7xl mx-auto px-6 h-14 flex items-center justify-between text-sm">
          <div className="flex items-center gap-3">
            <Shield className="w-5 h-5 text-blue-400" />
            <span className="font-bold tracking-widest uppercase">TraceBridge AI Systems</span>
            <span className="hidden md:inline text-slate-400 ml-4 border-l border-slate-700 pl-4">
              Enterprise Regulatory Intelligence Engine
            </span>
          </div>
          <div className="flex items-center gap-4">
            <div className="flex items-center gap-2 text-slate-400 text-xs hidden sm:flex">
              <Lock className="w-3 h-3" /> SOC-2 Compliant Environment
            </div>
            <Link href="/login" className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-1.5 rounded text-xs font-bold uppercase tracking-wider transition-colors">
              System Login
            </Link>
          </div>
        </div>
      </header>

      {/* Main Content Layout - 2 Columns Desktop */}
      <main className="flex-1 max-w-7xl mx-auto px-6 py-8 w-full grid lg:grid-cols-[1fr_350px] gap-8">
        
        {/* Left Column: Dense Information Architecture */}
        <div className="space-y-8">
          
          {/* Main Title Portal */}
          <div className="bg-white border border-slate-300 shadow-sm rounded-md p-8">
            <h1 className="text-3xl font-bold text-slate-900 mb-4 tracking-tight border-b border-slate-200 pb-4">
              Automated Traceability & Gap Detection
            </h1>
            <p className="text-slate-600 leading-relaxed text-sm mb-6 max-w-3xl">
              TraceBridge AI directly ingests complex Medical Device Software documentation (Risk Management, DHR, SRS, V&V Protocols) and performs multi-layered deterministic audits against FDA 510(k) and ISO standards. The engine replaces manual traceability matrix reviews with deterministic citations generated by a private Google Gemini semantic backend.
            </p>
            <div className="flex gap-4">
              <Link href="/login" className="bg-slate-900 hover:bg-slate-800 text-white px-5 py-2 rounded text-sm font-bold flex items-center gap-2 transition-colors">
                Initialize Audit Workflow <ArrowRight className="w-4 h-4" />
              </Link>
            </div>
          </div>

          {/* Engine Architecture Grid */}
          <div>
            <h2 className="text-sm font-bold text-slate-500 uppercase tracking-widest mb-4">Core Engine Capabilities</h2>
            <div className="grid md:grid-cols-3 gap-0 border border-slate-300 rounded-md bg-white overflow-hidden shadow-sm">
              <div className="p-6 border-b md:border-b-0 md:border-r border-slate-300">
                <Database className="w-6 h-6 text-blue-600 mb-3" />
                <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wider mb-2">Deterministic Rules</h3>
                <p className="text-xs text-slate-600 leading-relaxed">
                  153+ strict constraints hardcoded from IEC 62304, ISO 14971, and ISO 13485 mapped directly to a massive PostgreSQL architecture database.
                </p>
              </div>
              <div className="p-6 border-b md:border-b-0 md:border-r border-slate-300 bg-slate-50">
                <Brain className="w-6 h-6 text-emerald-600 mb-3" />
                <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wider mb-2">Semantic Evaluation</h3>
                <p className="text-xs text-slate-600 leading-relaxed">
                  Engine utilizes Google Gemini specialized routing to parse 100+ page clinical PDFs, extracting exact quotes to satisfy database constraints.
                </p>
              </div>
              <div className="p-6">
                <CheckCircle2 className="w-6 h-6 text-blue-800 mb-3" />
                <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wider mb-2">Verdict Triangulation</h3>
                <p className="text-xs text-slate-600 leading-relaxed">
                  Output is merged into strict JSON generating a mathematically sound trace matrix showing complete compliance, partial reviews, or missing evidence.
                </p>
              </div>
            </div>
          </div>

        </div>

        {/* Right Column: Workflows and Standards */}
        <div className="space-y-6">
          
          <div className="bg-white border border-slate-300 shadow-sm rounded-md overflow-hidden">
            <div className="bg-slate-100 border-b border-slate-300 px-4 py-3">
              <h2 className="text-xs font-bold text-slate-700 uppercase tracking-widest">Regulated Frameworks</h2>
            </div>
            <div className="p-0 divide-y divide-slate-200">
              <div className="p-4 hover:bg-slate-50 transition-colors">
                <div className="flex justify-between items-center mb-1">
                  <span className="text-sm font-bold text-slate-900">IEC 62304:2006</span>
                  <span className="text-[10px] bg-blue-100 text-blue-800 font-bold px-2 py-0.5 rounded uppercase">Active</span>
                </div>
                <p className="text-xs text-slate-600">Medical Device Software Lifecycle</p>
              </div>
              <div className="p-4 hover:bg-slate-50 transition-colors">
                <div className="flex justify-between items-center mb-1">
                  <span className="text-sm font-bold text-slate-900">ISO 14971:2019</span>
                  <span className="text-[10px] bg-blue-100 text-blue-800 font-bold px-2 py-0.5 rounded uppercase">Active</span>
                </div>
                <p className="text-xs text-slate-600">Risk Management Processing</p>
              </div>
              <div className="p-4 hover:bg-slate-50 transition-colors">
                <div className="flex justify-between items-center mb-1">
                  <span className="text-sm font-bold text-slate-900">ISO 13485:2016</span>
                  <span className="text-[10px] bg-blue-100 text-blue-800 font-bold px-2 py-0.5 rounded uppercase">Active</span>
                </div>
                <p className="text-xs text-slate-600">Quality Management Systems</p>
              </div>
            </div>
          </div>

          <div className="bg-white border border-slate-300 shadow-sm rounded-md overflow-hidden">
            <div className="bg-slate-100 border-b border-slate-300 px-4 py-3">
              <h2 className="text-xs font-bold text-slate-700 uppercase tracking-widest">Workflow Index</h2>
            </div>
            <div className="p-4 space-y-4">
              <div className="flex gap-3">
                <FileSearch className="w-4 h-4 text-slate-400 mt-0.5 flex-shrink-0" />
                <div>
                  <span className="text-sm font-bold text-slate-800 block">1. File Ingestion</span>
                  <span className="text-xs text-slate-500">Secure File API handles 20MB+ PDFs natively.</span>
                </div>
              </div>
              <div className="flex gap-3">
                <BarChart3 className="w-4 h-4 text-slate-400 mt-0.5 flex-shrink-0" />
                <div>
                  <span className="text-sm font-bold text-slate-800 block">2. Gap Generation</span>
                  <span className="text-xs text-slate-500">System throttles processing to abide by rate limits.</span>
                </div>
              </div>
              <div className="flex gap-3">
                <Shield className="w-4 h-4 text-slate-400 mt-0.5 flex-shrink-0" />
                <div>
                  <span className="text-sm font-bold text-slate-800 block">3. Result Output</span>
                  <span className="text-xs text-slate-500">Matrix formats directly for auditor review.</span>
                </div>
              </div>
            </div>
          </div>

        </div>
      </main>

      {/* Footer */}
      <footer className="bg-slate-900 text-slate-400 py-6 border-t border-slate-800">
        <div className="max-w-7xl mx-auto px-6 flex flex-col md:flex-row justify-between items-center text-xs">
          <div className="flex items-center gap-2 mb-4 md:mb-0">
            <Shield className="w-4 h-4 text-blue-500" />
            <span className="font-bold text-slate-300 tracking-wider">TRACEBRIDGE AI</span>
          </div>
          <div className="flex gap-6">
            <span>Enterprise Distribution Phase 2</span>
            <span>Cloud Infrastructure Active</span>
          </div>
        </div>
      </footer>
    </div>
  );
}
